packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@nestjs/core": true
  "@prisma/engines": true
  "@scarf/scarf": false
  "argon2": true
  "esbuild": true
  "prisma": true

onlyBuiltDependencies:
  - "@prisma/engines"
  - "@nestjs/core"
  - "argon2"
  - "esbuild"
  - "prisma"
